INSERT INTO Loc(id, addr, typ) VALUES (0, "1540 Adelaide St W, Toronto", 'Foster Home');
INSERT INTO Loc(id, addr, typ) VALUES (1, "1220 Queen St, Toronto", 'Foster Home');
INSERT INTO Loc(id, addr, typ) VALUES (2, "1130 Unversity Ave, Toronto", 'Foster Home');
INSERT INTO Loc(id, addr, typ) VALUES (3, "1000 Bloor St, Toronto", 'Shelter');
INSERT INTO Loc(id, addr, typ) VALUES (4, "1200 Bloor St, Toronto", 'Shelter');
INSERT INTO Loc(id, addr, typ) VALUES (5, "923 Danforth Ave, Toronto", 'Store');
INSERT INTO Loc(id, addr, typ) VALUES (6, "857 Danforth Ave, Toronto", 'Store');
INSERT INTO Loc(id, addr, typ) VALUES (7, "3240 Bay St, Toronto", 'Vet');
INSERT INTO Loc(id, addr, typ) VALUES (8, "2102 Bay St, Toronto", 'Volunteer Centre');
INSERT INTO Loc(id, addr, typ) VALUES (9, "1958 Bay St, Toronto", 'Volunteer Centre');