ALTER TABLE Cat (
    ADD CONSTRAINT fKeyLocID FOREIGN KEY (locId) REFERENCES Loc(id),
    ADD CONSTRAINT fKeyAdoptID  FOREIGN KEY (adopterID) REFERENCES Adopter(id)
);

ALTER TABLE Adopter (
    ADD CONSTRAINT fKeyStaffConfirmation FOREIGN KEY (staffConfirmationID) REFERENCES Staff(id),
    ADD CONSTRAINT fKeyACatID FOREIGN KEY (catId) REFERENCES Cat(id)
);

ALTER TABLE Health (
    ADD CONSTRAINT fKeyHCatID FOREIGN KEY (catId) REFERENCES Cat(id)
);

ALTER TABLE Staff (
    ADD CONSTRAINT fKeySLocID FOREIGN KEY (locID) REFERENCES Loc(id)
);